IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE name=N'Users')
BEGIN
	ALTER TABLE Users ADD PhoneNo VARCHAR(20)
	ALTER TABLE Users ADD Email VARCHAR(50)
	ALTER TABLE Users ADD DeliveryAddress VARCHAR(200)
END